<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $barangs = [

            // ── MINYAK PIJAT ─────────────────────────────────────
            [
                'kode_barang'       => 'MYK-001',
                'nama_barang'       => 'Minyak Pijat Zaitun',
                'kategori'          => 'minyak_pijat',
                'satuan'            => 'botol',
                'stok_awal'         => 20,
                'stok_masuk'        => 10,
                'stok_keluar'       => 8,
                'stok_aktual'       => 22,
                'harga_beli'        => 35000,
                'harga_jual'        => 50000,
                'stok_minimum'      => 5,
                'lokasi_simpan'     => 'Lemari A, Rak 1',
                'tanggal_kadaluarsa' => '2026-12-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'MYK-002',
                'nama_barang'       => 'Minyak Pijat Lavender',
                'kategori'          => 'minyak_pijat',
                'satuan'            => 'botol',
                'stok_awal'         => 15,
                'stok_masuk'        => 5,
                'stok_keluar'       => 6,
                'stok_aktual'       => 14,
                'harga_beli'        => 40000,
                'harga_jual'        => 55000,
                'stok_minimum'      => 5,
                'lokasi_simpan'     => 'Lemari A, Rak 1',
                'tanggal_kadaluarsa' => '2026-10-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'MYK-003',
                'nama_barang'       => 'Minyak Pijat Aromaterapi Eucalyptus',
                'kategori'          => 'minyak_pijat',
                'satuan'            => 'botol',
                'stok_awal'         => 10,
                'stok_masuk'        => 0,
                'stok_keluar'       => 4,
                'stok_aktual'       => 6,
                'harga_beli'        => 45000,
                'harga_jual'        => 60000,
                'stok_minimum'      => 5,
                'lokasi_simpan'     => 'Lemari A, Rak 2',
                'tanggal_kadaluarsa' => '2026-08-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Stok hampir habis, segera reorder',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── LOTION ───────────────────────────────────────────
            [
                'kode_barang'       => 'LOT-001',
                'nama_barang'       => 'Lotion Body Cream Pelembab',
                'kategori'          => 'lotion',
                'satuan'            => 'botol',
                'stok_awal'         => 25,
                'stok_masuk'        => 10,
                'stok_keluar'       => 12,
                'stok_aktual'       => 23,
                'harga_beli'        => 28000,
                'harga_jual'        => 40000,
                'stok_minimum'      => 8,
                'lokasi_simpan'     => 'Lemari A, Rak 3',
                'tanggal_kadaluarsa' => '2027-01-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'LOT-002',
                'nama_barang'       => 'Lotion Scrub Lulur Kopi',
                'kategori'          => 'lotion',
                'satuan'            => 'pcs',
                'stok_awal'         => 12,
                'stok_masuk'        => 6,
                'stok_keluar'       => 5,
                'stok_aktual'       => 13,
                'harga_beli'        => 32000,
                'harga_jual'        => 45000,
                'stok_minimum'      => 5,
                'lokasi_simpan'     => 'Lemari A, Rak 3',
                'tanggal_kadaluarsa' => '2026-09-30',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── HANDUK ───────────────────────────────────────────
            [
                'kode_barang'       => 'HDK-001',
                'nama_barang'       => 'Handuk Besar Putih',
                'kategori'          => 'handuk',
                'satuan'            => 'lembar',
                'stok_awal'         => 30,
                'stok_masuk'        => 10,
                'stok_keluar'       => 5,
                'stok_aktual'       => 35,
                'harga_beli'        => 45000,
                'harga_jual'        => 0,
                'stok_minimum'      => 10,
                'lokasi_simpan'     => 'Lemari B, Rak 1',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Inventaris, bukan untuk dijual',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'HDK-002',
                'nama_barang'       => 'Handuk Kecil / Lap Muka',
                'kategori'          => 'handuk',
                'satuan'            => 'lembar',
                'stok_awal'         => 50,
                'stok_masuk'        => 20,
                'stok_keluar'       => 10,
                'stok_aktual'       => 60,
                'harga_beli'        => 15000,
                'harga_jual'        => 0,
                'stok_minimum'      => 15,
                'lokasi_simpan'     => 'Lemari B, Rak 1',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Inventaris, bukan untuk dijual',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'HDK-003',
                'nama_barang'       => 'Sarung Bantal',
                'kategori'          => 'handuk',
                'satuan'            => 'lembar',
                'stok_awal'         => 20,
                'stok_masuk'        => 0,
                'stok_keluar'       => 2,
                'stok_aktual'       => 18,
                'harga_beli'        => 20000,
                'harga_jual'        => 0,
                'stok_minimum'      => 6,
                'lokasi_simpan'     => 'Lemari B, Rak 2',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── ALAT PIJAT ───────────────────────────────────────
            [
                'kode_barang'       => 'ALP-001',
                'nama_barang'       => 'Batu Giok / Massage Stone',
                'kategori'          => 'alat',
                'satuan'            => 'set',
                'stok_awal'         => 5,
                'stok_masuk'        => 2,
                'stok_keluar'       => 1,
                'stok_aktual'       => 6,
                'harga_beli'        => 150000,
                'harga_jual'        => 0,
                'stok_minimum'      => 2,
                'lokasi_simpan'     => 'Lemari C, Rak 1',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Alat inventaris terapis',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'ALP-002',
                'nama_barang'       => 'Roller Kayu Pijat Punggung',
                'kategori'          => 'alat',
                'satuan'            => 'pcs',
                'stok_awal'         => 8,
                'stok_masuk'        => 0,
                'stok_keluar'       => 2,
                'stok_aktual'       => 6,
                'harga_beli'        => 35000,
                'harga_jual'        => 0,
                'stok_minimum'      => 3,
                'lokasi_simpan'     => 'Lemari C, Rak 1',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'ALP-003',
                'nama_barang'       => 'Matras Pijat Portabel',
                'kategori'          => 'alat',
                'satuan'            => 'pcs',
                'stok_awal'         => 4,
                'stok_masuk'        => 1,
                'stok_keluar'       => 0,
                'stok_aktual'       => 5,
                'harga_beli'        => 500000,
                'harga_jual'        => 0,
                'stok_minimum'      => 2,
                'lokasi_simpan'     => 'Gudang',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Digunakan untuk home service',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── KEBERSIHAN ───────────────────────────────────────
            [
                'kode_barang'       => 'KBR-001',
                'nama_barang'       => 'Sabun Cuci Tangan Antiseptik',
                'kategori'          => 'kebersihan',
                'satuan'            => 'botol',
                'stok_awal'         => 10,
                'stok_masuk'        => 5,
                'stok_keluar'       => 7,
                'stok_aktual'       => 8,
                'harga_beli'        => 18000,
                'harga_jual'        => 0,
                'stok_minimum'      => 3,
                'lokasi_simpan'     => 'Kamar Mandi',
                'tanggal_kadaluarsa' => '2026-12-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'KBR-002',
                'nama_barang'       => 'Tisu Box',
                'kategori'          => 'kebersihan',
                'satuan'            => 'box',
                'stok_awal'         => 20,
                'stok_masuk'        => 10,
                'stok_keluar'       => 15,
                'stok_aktual'       => 15,
                'harga_beli'        => 12000,
                'harga_jual'        => 0,
                'stok_minimum'      => 5,
                'lokasi_simpan'     => 'Lemari D',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'KBR-003',
                'nama_barang'       => 'Plastik Alas Kaki Sekali Pakai',
                'kategori'          => 'kebersihan',
                'satuan'            => 'pack',
                'stok_awal'         => 10,
                'stok_masuk'        => 5,
                'stok_keluar'       => 8,
                'stok_aktual'       => 7,
                'harga_beli'        => 15000,
                'harga_jual'        => 0,
                'stok_minimum'      => 3,
                'lokasi_simpan'     => 'Lemari D',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── BAHAN LULUR ──────────────────────────────────────
            [
                'kode_barang'       => 'LLR-001',
                'nama_barang'       => 'Lulur Beras Kuning Tradisional',
                'kategori'          => 'bahan_lulur',
                'satuan'            => 'kg',
                'stok_awal'         => 5,
                'stok_masuk'        => 3,
                'stok_keluar'       => 2,
                'stok_aktual'       => 6,
                'harga_beli'        => 80000,
                'harga_jual'        => 0,
                'stok_minimum'      => 2,
                'lokasi_simpan'     => 'Lemari A, Rak 4',
                'tanggal_kadaluarsa' => '2025-12-31',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => 'Bahan baku lulur tradisional',
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
            [
                'kode_barang'       => 'LLR-002',
                'nama_barang'       => 'Masker Tanah Liat (Clay Mask)',
                'kategori'          => 'bahan_lulur',
                'satuan'            => 'pcs',
                'stok_awal'         => 15,
                'stok_masuk'        => 5,
                'stok_keluar'       => 6,
                'stok_aktual'       => 14,
                'harga_beli'        => 25000,
                'harga_jual'        => 0,
                'stok_minimum'      => 4,
                'lokasi_simpan'     => 'Lemari A, Rak 4',
                'tanggal_kadaluarsa' => '2026-06-30',
                'tanggal_kroscek'   => $now->toDateString(),
                'petugas_kroscek'   => 'Admin',
                'catatan'           => null,
                'status'            => 'aktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── NONAKTIF (contoh barang tidak terpakai) ──────────
            [
                'kode_barang'       => 'ALP-099',
                'nama_barang'       => 'Steamer Wajah Lama',
                'kategori'          => 'alat',
                'satuan'            => 'pcs',
                'stok_awal'         => 1,
                'stok_masuk'        => 0,
                'stok_keluar'       => 0,
                'stok_aktual'       => 1,
                'harga_beli'        => 350000,
                'harga_jual'        => 0,
                'stok_minimum'      => 1,
                'lokasi_simpan'     => 'Gudang',
                'tanggal_kadaluarsa' => null,
                'tanggal_kroscek'   => null,
                'petugas_kroscek'   => null,
                'catatan'           => 'Rusak, menunggu perbaikan',
                'status'            => 'nonaktif',
                'created_at'        => $now,
                'updated_at'        => $now,
            ],
        ];

        DB::table('barangs')->insert($barangs);

        $this->command->info('✅ BarangSeeder: ' . count($barangs) . ' barang berhasil di-seed.');
    }
}
