<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Seed data pelanggan dari export Majoo - Koichi Refleksi
     * Total  : 366 pelanggan (VVIP: 12, VIP: 1, Regular: 353)
     *
     * Catatan: user_id di-set 1 (default). Sesuaikan jika perlu
     *          assign ke user/kasir yang berbeda.
     */
    public function run(): void
    {
        $customers = [
            ['user_id' => 1, 'name' => 'Uun - Tan Fenny', 'phone' => '081911859333', 'address' => 'Jl. Setrayasa X no.3A', 'email' => null, 'ulang_tahun' => '1959-12-16'],
            ['user_id' => 1, 'name' => 'David Tedja', 'phone' => '082117109990', 'address' => 'Jl. Setrayasa X no.3A', 'email' => null, 'ulang_tahun' => '1986-02-15'],
            ['user_id' => 1, 'name' => 'Liana Regina Tedja', 'phone' => '081806031000', 'address' => 'Taman Cipto', 'email' => null, 'ulang_tahun' => '1987-03-06'],
            ['user_id' => 1, 'name' => 'Ronny Antonius', 'phone' => '08122135114', 'address' => 'Taman Cipto', 'email' => null, 'ulang_tahun' => '1982-04-23'],
            ['user_id' => 1, 'name' => 'Cherish Noella Halison', 'phone' => '087809121000', 'address' => 'Taman Cipto', 'email' => null, 'ulang_tahun' => '2017-12-09'],
            ['user_id' => 1, 'name' => 'Brielle Nasya Alena', 'phone' => '082260321502', 'address' => 'Taman Cipto', 'email' => null, 'ulang_tahun' => '2022-05-05'],
            ['user_id' => 1, 'name' => 'Adi Setiawan D.', 'phone' => '08112243789', 'address' => 'Sukawarna Baru', 'email' => null, 'ulang_tahun' => '2025-10-26'],
            ['user_id' => 1, 'name' => 'Anand Khrisna D.', 'phone' => '0811234898', 'address' => 'Sukawarna Baru', 'email' => null, 'ulang_tahun' => '2010-03-25'],
            ['user_id' => 1, 'name' => 'Mariawati', 'phone' => '08112348968', 'address' => 'Sukawarna Baru', 'email' => null, 'ulang_tahun' => '1943-03-06'],
            ['user_id' => 1, 'name' => 'Herniaty', 'phone' => '08112343788', 'address' => 'Sukawarna Baru', 'email' => null, 'ulang_tahun' => '1971-03-05'],
            ['user_id' => 1, 'name' => 'Rosiliarani', 'phone' => '0888888888888', 'address' => 'Jl. Setrayasa X no.3A', 'email' => null, 'ulang_tahun' => '1989-10-20'],
            ['user_id' => 1, 'name' => 'Ian', 'phone' => '08888888888888', 'address' => 'Jl. Setrayasa X no.3A', 'email' => null, 'ulang_tahun' => '2025-10-28'],
            ['user_id' => 1, 'name' => 'Hariyo', 'phone' => '081220047060', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fandy', 'phone' => '089670009867', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Widya', 'phone' => '08892721760', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fitri', 'phone' => '0895415447220', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Budiman', 'phone' => '0818110782', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Deny', 'phone' => '081222022220', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Abdan', 'phone' => '085295511674', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Michael', 'phone' => '081226620884', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dr Joice', 'phone' => '089503464040', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fitri', 'phone' => '0882005068857', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yota', 'phone' => '081320001238', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Latifa', 'phone' => '0811336575', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tria', 'phone' => '082258866778', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Halimah', 'phone' => '082243413902', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bu Evi', 'phone' => '082133399555', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Melisa', 'phone' => '082130090999', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Nelly', 'phone' => '081312301297', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bu Nanik', 'phone' => '089698298980', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Irma', 'phone' => '08987305128', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Keziem', 'phone' => '087882728778', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Windu', 'phone' => '089627500007', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Christ', 'phone' => '081929999168', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hendry', 'phone' => '089661381245', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Michael', 'phone' => '0819840163', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Erik', 'phone' => '087823353800', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Krisnawan', 'phone' => '087777723222', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tyas', 'phone' => '085721154145', 'address' => 'Cirebon ', 'email' => null, 'ulang_tahun' => '1990-02-06'],
            ['user_id' => 1, 'name' => 'Vandi', 'phone' => '081328067828', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-05'],
            ['user_id' => 1, 'name' => 'Tami', 'phone' => '089670009494', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-05'],
            ['user_id' => 1, 'name' => 'Dona', 'phone' => '081122220607', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-05'],
            ['user_id' => 1, 'name' => 'Rosalinda', 'phone' => '082120794310', 'address' => '', 'email' => null, 'ulang_tahun' => '1999-12-08'],
            ['user_id' => 1, 'name' => 'Riko', 'phone' => '082317067141', 'address' => '', 'email' => null, 'ulang_tahun' => '1993-06-06'],
            ['user_id' => 1, 'name' => 'Heni', 'phone' => '081332777777', 'address' => 'Cirebon ', 'email' => null, 'ulang_tahun' => '1982-05-03'],
            ['user_id' => 1, 'name' => 'Astri', 'phone' => '081909979900', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Marlien', 'phone' => '085220200999', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Arifin', 'phone' => '089613747470', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Edwin', 'phone' => '081806284444', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ervina', 'phone' => '08112019280', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Susi', 'phone' => '081222223525', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Juan', 'phone' => '082272271993', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Haliem', 'phone' => '0821300909999', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Putri', 'phone' => '081993925472', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Efendi', 'phone' => '081564618564', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Pak Aman', 'phone' => '081804646499', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Krista', 'phone' => '081224888887', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Inti Cendana', 'phone' => '08987674889', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Muhaemin', 'phone' => '081320285071', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ifan', 'phone' => '082115542995', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Eiben', 'phone' => '085864682137', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Robi', 'phone' => '085793116668', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bambang', 'phone' => '082214108356', 'address' => '', 'email' => null, 'ulang_tahun' => '1981-05-29'],
            ['user_id' => 1, 'name' => 'Indra', 'phone' => '089660643438', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Natali', 'phone' => '0818680672', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Imelda', 'phone' => '08122212480', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ardian', 'phone' => '08122345245', 'address' => '', 'email' => null, 'ulang_tahun' => '1990-05-19'],
            ['user_id' => 1, 'name' => 'Suci', 'phone' => '085659710000', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-13'],
            ['user_id' => 1, 'name' => 'Esti', 'phone' => '08122202623', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-13'],
            ['user_id' => 1, 'name' => 'Novi', 'phone' => '089675087290', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dr Vina', 'phone' => '087778587353', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Jeannet', 'phone' => '0895605925644', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Beye', 'phone' => '08987326578', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Vina', 'phone' => '085294373737', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Erin', 'phone' => '085862696764', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Steven', 'phone' => '085973212566', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Antony', 'phone' => '087744375325', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Alex', 'phone' => '0811159178', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Karolina', 'phone' => '087829026522', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Budi', 'phone' => '081322988555', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'David', 'phone' => '089635079819', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Seto', 'phone' => '085117607735', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Angga', 'phone' => '082316729723', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Samuel', 'phone' => '08176601122', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Norman', 'phone' => '081909928088', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sansan', 'phone' => '081223828278', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Erika', 'phone' => '089630844794', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kelvin', 'phone' => '08575311919', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Budi', 'phone' => '085846989877', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Triyas', 'phone' => '089660703420', 'address' => '', 'email' => null, 'ulang_tahun' => '1994-04-26'],
            ['user_id' => 1, 'name' => 'Rudi', 'phone' => '081223870555', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lili', 'phone' => '08122459688', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sandra', 'phone' => '089632730772', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-20'],
            ['user_id' => 1, 'name' => 'Rega', 'phone' => '0818800301', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dian', 'phone' => '085559426922', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-11-20'],
            ['user_id' => 1, 'name' => 'Zeno', 'phone' => '08997733333', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Idah', 'phone' => '082257119988', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yasmin', 'phone' => '081394646135', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ahmad', 'phone' => '0812320080121', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kiki', 'phone' => '082236846951', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Alny', 'phone' => '085659684681', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yudha', 'phone' => '0811833830', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yudha', 'phone' => '081703010439', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Cynthia', 'phone' => '081931134212', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Risda', 'phone' => '081802115142', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Maya', 'phone' => '087887400770', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Christine', 'phone' => '089664282837', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Putri', 'phone' => '089655752286', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Krisna', 'phone' => '0811977660', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Christian', 'phone' => '085722007847', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dyah', 'phone' => '085724750688', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ci Suna', 'phone' => '087881507186', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sekar', 'phone' => '082321222960', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Siska', 'phone' => '085216333567', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tika', 'phone' => '082137137742', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ela', 'phone' => '082324241324', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Iren', 'phone' => '08112333920', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tati', 'phone' => '088971829299', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Susan', 'phone' => '08112426999', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rahmat', 'phone' => '087824320991', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Meita', 'phone' => '08111806062', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Diah', 'phone' => '0821100041770', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Arvin', 'phone' => '08777775200', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Pak Iing', 'phone' => '0816618588', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ida', 'phone' => '081219997337', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bari', 'phone' => '082240225889', 'address' => '', 'email' => null, 'ulang_tahun' => '1995-01-05'],
            ['user_id' => 1, 'name' => 'Salma', 'phone' => '081228074089', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hendra', 'phone' => '083120121633', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Suci', 'phone' => '081322882810', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Olivia', 'phone' => '087775429948', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ardi', 'phone' => '0000000000', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Evan', 'phone' => '08179092500', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Theresa', 'phone' => '087888879010', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lia', 'phone' => '08776471469', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Syifa', 'phone' => '087764714694', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dama', 'phone' => '083710565518', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Devi', 'phone' => '083824187479', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Mira', 'phone' => '08113545984', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lian', 'phone' => '082115647414', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Pak Bambang', 'phone' => '08952996275', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Cahyadi', 'phone' => '08194920778', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dinan', 'phone' => '085559122837', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rangga', 'phone' => '081214434797', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ica', 'phone' => '089629611605', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fitria', 'phone' => '089505889101', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Selin', 'phone' => '087829487878', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Adrian', 'phone' => '081298301618', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lia', 'phone' => '082115000235', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Stef', 'phone' => '0895336753331', 'address' => 'cirebon ', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fika', 'phone' => '08122218189', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Talita', 'phone' => '082234547098', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rahma', 'phone' => '082128473188', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Atri', 'phone' => '081227101736', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Diana', 'phone' => '087733550677', 'address' => '', 'email' => null, 'ulang_tahun' => '2025-12-12'],
            ['user_id' => 1, 'name' => 'Indraa', 'phone' => '0111523123', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kiki', 'phone' => '081122222256', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yosy', 'phone' => '081389840462', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bayu', 'phone' => '081288222998', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lukas', 'phone' => '08170697778', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tia', 'phone' => '089656965605', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Oscar', 'phone' => '08992720899', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Galih', 'phone' => '081122888884', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Nathalie', 'phone' => '08118160795', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sela', 'phone' => '083840176862', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Chang Yi', 'phone' => '08231599869', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Niko', 'phone' => '08118034581', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Teguh', 'phone' => '08161818418', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Clara', 'phone' => '081802312308', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dewi', 'phone' => '082322630344', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Angelica', 'phone' => '087706664333', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ryan Aditya', 'phone' => '087875797176', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Evan', 'phone' => '082126610413', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Syifa', 'phone' => '087709174126', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Irma', 'phone' => '085864306210', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Mia', 'phone' => '081284858588', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fuji', 'phone' => '081320980042', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Wahyu', 'phone' => '085724027857', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Angga', 'phone' => '085280260001', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andi', 'phone' => '08179885824', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ayu', 'phone' => '085649798133', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Gween', 'phone' => '087709234418', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Stefani', 'phone' => '08112011388', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andri', 'phone' => '085317575858', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rossy Adhystia', 'phone' => '082197083903', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rizki', 'phone' => '089654930423', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fathya', 'phone' => '082117368693', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => '821-2050-4270', 'phone' => '082120504270', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Meta', 'phone' => '081218691001', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Wisna', 'phone' => '081805685686', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Mela', 'phone' => '08977012005', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Monic', 'phone' => '0818230723', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Latifah', 'phone' => '089697006902', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Parulian', 'phone' => '08111827682', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sarah', 'phone' => '082120925973', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Julius', 'phone' => '082117671276', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Taufik', 'phone' => '082325435993', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Halim', 'phone' => '085782283888', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lisa', 'phone' => '082226495331', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yohan', 'phone' => '085282710302', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Luna', 'phone' => '08987013332', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Salsa', 'phone' => '082221659383', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hikmah', 'phone' => '087812776245', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Evan', 'phone' => '085148486587', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dede', 'phone' => '0896962210005', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kristin', 'phone' => '081288208856', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Umi Rodiyah', 'phone' => '085720362474', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tommy', 'phone' => '082115130489', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fitri', 'phone' => '085220018689', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hardi', 'phone' => '087822295966', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hari', 'phone' => '081223332101', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hegi', 'phone' => '081324785909', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Edo', 'phone' => '08112407770', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dewi Kusuma', 'phone' => '082130190777', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Erni', 'phone' => '08122205098', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Saiful', 'phone' => '082115239545', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Agus', 'phone' => '0818715050', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dane', 'phone' => '081239993317', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Intan', 'phone' => '083824308167', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Legisya', 'phone' => '081111188180', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Nikki', 'phone' => '085793365591', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Maya', 'phone' => '089664837721', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Jujun', 'phone' => '08112421003', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hemi', 'phone' => '08112400626', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Arin', 'phone' => '083891537194', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Irwin', 'phone' => '081804699388', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Gia', 'phone' => '087829388249', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Grace', 'phone' => '089620534540', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Anggita', 'phone' => '081282123474', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bayu', 'phone' => '0895393956570', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dini', 'phone' => '08112041001', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Santi', 'phone' => '082117271845', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Miming', 'phone' => '081325019344', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Winar', 'phone' => '082260061861', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ane', 'phone' => '08170697776', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fero', 'phone' => '085280576950', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ugi', 'phone' => '087785613880', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Intan Nurul', 'phone' => '08212050427042', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Wahyu', 'phone' => '083156693572', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kusnan', 'phone' => '081285151501', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lani', 'phone' => '081218379012', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Agnes', 'phone' => '089502926176', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bunga', 'phone' => '0882002304704', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Deny', 'phone' => '0816642537', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Pie Jay', 'phone' => '08132433321', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lina', 'phone' => '089659394441', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Wahyu', 'phone' => '081717197979', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Anhoa', 'phone' => '08179060083', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Aming', 'phone' => '0818239293', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dina', 'phone' => '082240666332', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sandy Caesario W', 'phone' => '0819233669', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Megawati', 'phone' => '08997317416', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Olin', 'phone' => '089660326971', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Intan', 'phone' => '089660785786', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Devin', 'phone' => '082230000262', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Oliv', 'phone' => '089606020781', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ody', 'phone' => '082111696777', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lyana', 'phone' => '085703479919', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Inggri', 'phone' => '081269829677', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Jonatan', 'phone' => '0818237350', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kartika', 'phone' => '081564700701', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ben', 'phone' => '08111341346', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Halim', 'phone' => '085720301367', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ida', 'phone' => '085224544525', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Faradiba Divani', 'phone' => '08823131505', 'address' => '', 'email' => null, 'ulang_tahun' => '2003-01-04'],
            ['user_id' => 1, 'name' => 'Ida K', 'phone' => '081320769108', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lionnita', 'phone' => '087882158075', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tomy', 'phone' => '0822114752132', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Pepy', 'phone' => '081320145451', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Handoko', 'phone' => '081911325100', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Frety', 'phone' => '085973044122', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sadro', 'phone' => '082122008523', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hari', 'phone' => '082315567874', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Shagy', 'phone' => '087789245855', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Hendri', 'phone' => '081218965781', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Topan', 'phone' => '081122208888', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Muji', 'phone' => '08238712892', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Windo', 'phone' => '081312575736', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fitri', 'phone' => '085156565153', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Habibi', 'phone' => '089619393949', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Indy', 'phone' => '08112244122', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dian Almaidah', 'phone' => '081372690587', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andri', 'phone' => '08999020556', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Anastasia', 'phone' => '0817110468', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Santika', 'phone' => '085724304171', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tati', 'phone' => '085862800987', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Tedy', 'phone' => '082318762213', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Keysia', 'phone' => '081312756099', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fery', 'phone' => '085147365781', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Putri Nindar Ayu', 'phone' => '089633315218', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Daniel Tjongari', 'phone' => '081231836686', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Daimah', 'phone' => '085722190098', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Jay', 'phone' => '08999339776', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Asmina', 'phone' => '08122131188', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sonya', 'phone' => '08122212381', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fey', 'phone' => '082138132912', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rahma', 'phone' => '087814987675', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Susan', 'phone' => '08122127955', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Teguh', 'phone' => '08125935788', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Bu Agus', 'phone' => '081221727272', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Sulis', 'phone' => '082127142222', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Vian', 'phone' => '087724991916', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Cristine', 'phone' => '0895614101020', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Eva', 'phone' => '0812307623060', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Abidah', 'phone' => '082315811403', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Eko', 'phone' => '081253638176', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yohan', 'phone' => '081313238880', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lazuardi', 'phone' => '089525081383', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Anisa', 'phone' => '082119662669', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kartini', 'phone' => '089662067673', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Agung', 'phone' => '082228202220', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dane', 'phone' => '081239993811', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'April', 'phone' => '081214809803', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Arul', 'phone' => '085294739773', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Susan', 'phone' => '08112402634', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Eka', 'phone' => '08122208288', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Leo', 'phone' => '01136850158', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kiki', 'phone' => '082117822991', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Arin', 'phone' => '085223404288', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Imah', 'phone' => '081324722371', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fety', 'phone' => '0817718703', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Devi.', 'phone' => '081389898299', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Lisa.', 'phone' => '08156859330', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andre Lie', 'phone' => '085721861849', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yanti', 'phone' => '0000', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dita', 'phone' => '08170580002', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kadewi', 'phone' => '08977083369', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Kuntari', 'phone' => '00000000', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Layla', 'phone' => '081232300788', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Siska', 'phone' => '085324402552', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Teddy', 'phone' => '085717211751', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Egi Mahendra', 'phone' => '085721522113', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Leo', 'phone' => '081223722525', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Leo.', 'phone' => '000', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Mei', 'phone' => '082211771652', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yandi / joshua', 'phone' => '0895401100020', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Aldila Maudina Puspa', 'phone' => '089660624926', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Yuri Rizki', 'phone' => '082117371987', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Cici (Revlon Toko Eka)', 'phone' => '081947028466', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Eno', 'phone' => '083898797544', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ling', 'phone' => '087876032677', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Joni', 'phone' => '0895337228707', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Syarah', 'phone' => '087818520280', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Magdalena Wijayandi', 'phone' => '085353725231', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Prisca', 'phone' => '085640788291', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Budiman', 'phone' => '085224919909', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Heri', 'phone' => '085624615280', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Herri', 'phone' => '081296797778', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andreas', 'phone' => '085224579565', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rizki', 'phone' => '083180784698', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Harry', 'phone' => '089604738459', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Amelia', 'phone' => '087730404069', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Andri', 'phone' => '085199203616', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Melinda', 'phone' => '085727967204', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Aldi Prasetia', 'phone' => '081324556323', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Gani', 'phone' => '085738869904', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Adrian', 'phone' => '0818829385', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Indah', 'phone' => '082115443029', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Melvina', 'phone' => '08190808708835', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Rafli', 'phone' => '081314857870', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Indra Bagus', 'phone' => '082260906047', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Luki', 'phone' => '081380999892', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Fanik', 'phone' => '08156401661', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dadang', 'phone' => '08122108671', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Novianti', 'phone' => '082115156767', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Ineke', 'phone' => '081262226210', 'address' => '', 'email' => null, 'ulang_tahun' => null],
            ['user_id' => 1, 'name' => 'Dimas Junot', 'phone' => '081910013666', 'address' => '', 'email' => null, 'ulang_tahun' => null],
        ];

        foreach ($customers as $data) {
            Customer::create($data);
        }
    }
}
